name: ec_2021_gliderviz
channels:
  - conda-forge
dependencies:
  - python=3.7
  - geoviews
  - gsw
  - holoviews=1.14.2
  - panel=0.11.1
  - hvplot=0.7.1
  - jupyterlab=2
  - jupyter-panel-proxy
  - netcdf4=1.5.4
  - pandas=1.2.3
  - xarray=0.16.2
  - glidertools
